### ISSUE TITLE
Publish to NPM

### ISSUE THREAD

**Issue by ajgrover** [converge/instapy-dashboard#30]
It's quick to publish a package to NPM and would make it a bit easier to manage the install process! Also keeps it in line with the way you install instapy now. If you're installing this for use on a server (or even locally) there's really no need to clone the repo itself.

I'm imagining something like this:
```bash
$ pip install instapy
$ npm install -g instapy-dashboard
$ instapy-dashboard & # or you could put `npm run instapy-dashboard` in your package.json
$ python run.py
```

**Comment by ajgrover** [comment]
actually, i looked at this a little today, and i guess it's not as easy as i initially imagined

**Comment by converge** [comment]
I see. We could say that the current status of the project is "in development", that's why there isn't much more information about how to deploy it.

Before the next step, we will need a basic credential system. I'm just waiting for InstaPy update the database approach (sounds like it will move to MongoDB), and it will be more concise to implement the credential system.

**Comment by ajgrover** [comment]
interesting, do you mind linking me to the discussion?

for context, i was looking into what it would take to get a full featured (user management, instagram credential management, etc.) web interface up and running and this seemed like a good option! although at the moment the amount of information you can get out of instapy is pretty limited. if they actually end up using a database approach, or if there's a similar library that is a bit more low-level and allows you to handle the record keeping yourself, it would be quite helpful
